### ISSUE TITLE
[BUG] Misalignment of Thermo Data in dummped YAML file

### ISSUE THREAD

**Issue by yueyericardo** [lammps/lammps#3799]
**Summary**

When comparing the thermo output from the LAMMPS log file to the thermo output in the YAML dump file, I've noticed a difference for the initial timestep (0). In the YAML file, the thermo data for timestep 0 appears to be invalid or meaningless, and does not align with the thermo data from the LAMMPS log file.

As can be observed from the following snipptes, the thermo data for timestep 1 in the YAML file matches the data for timestep 0 in the LAMMPS log file. This pattern continues, causing all thermo data in the YAML file to appear one timestep behind the data in the LAMMPS log file. This discrepancy is causing significant confusion when analyzing the results.

Here's the snippet of the thermo data from the LAMMPS log file for the first few timesteps:
```
keywords: ['Step', 'PotEng', 'KinEng', 'TotEng', 'Temp', 'Press', 'Volume', 'Density', 'c_press[1]', 'c_press[2]', 'c_press[3]', 'c_press[4]', 'c_press[5]', 'c_press[6]', ]
data:
  - [0, -479421.691781166, 0, -479421.691781166, 0, 7864.6559730265, 512, 0.5842697004374, 7720.76660099825, 11152.0949780855, 4721.10633999577, 1861.50214355324, 1598.1849785235, -415.12650213297, ]
  - [1, -479421.702029192, 0.0102364454473237, -479421.691792747, 0.118417769523395, 7835.45786565537, 512, 0.5842697004374, 7691.68586639822, 11120.8612768112, 4693.82645375669, 1858.27672454755, 1594.21198346326, -410.512686839785, ]
  - [2, -479421.7325883, 0.0407611223356872, -479421.691827178, 0.471534891198419, 7748.08050985201, 512, 0.5842697004374, 7604.65988968182, 11027.4111059135, 4612.17053396075, 1848.63117983296, 1582.32645091386, -396.700177502109, ]
  - [3, -479421.782908429, 0.0910248771390507, -479421.691883551, 1.05299861923903, 7603.17544035678, 512, 0.5842697004374, 7460.34501669082, 10872.4869496582, 4476.69435472129, 1832.66461502789, 1562.61735161485, -373.785220639499, ]
  - [4, -479421.852088677, 0.160128297181147, -479421.691960379, 1.85240432212028, 7401.79815680349, 512, 0.5842697004374, 7259.81679407431, 10657.2768161709, 4288.30086016521, 1810.50727012551, 1535.25774010898, -341.898159687684, ]
...
```

And here's the corresponding output in the YAML dump file for the same timesteps:
```
creator: LAMMPS
timestep: 0
units: real
time: 0
natoms: 30
boundary: [ p, p, p, p, p, p, ]
thermo:
  - keywords: [ Step, PotEng, KinEng, TotEng, Temp, Press, Volume, Density, Pxx, Pyy, Pzz, Pxy, Pxz, Pyz, ]
  - data: [ 0, -nan, 0, -nan, 1.9090011553e-313, 5.43223878283e-312, 512, 0.5842697004374003, 4.6600098255045e-310, 0, 4.6601149565388e-310, 4.787190529701563e+180, 1.8155354104984654e-134, 5.817149395556409e+180, ]
...
---
creator: LAMMPS
timestep: 1
units: real
time: 0.1
natoms: 30
boundary: [ p, p, p, p, p, p, ]
thermo:
  - keywords: [ Step, PotEng, KinEng, TotEng, Temp, Press, Volume, Density, Pxx, Pyy, Pzz, Pxy, Pxz, Pyz, ]
  - data: [ 1, -479421.6917811662, 0, -479421.6917811662, 0, 7864.655973026495, 512, 0.5842697004374003, 7720.766600998249, 11152.094978085463, 4721.106339995775, 1861.5021435532385, 1598.1849785234965, -415.12650213297024, ]
...
---
creator: LAMMPS
timestep: 2
units: real
time: 0.2
natoms: 30
boundary: [ p, p, p, p, p, p, ]
thermo:
  - keywords: [ Step, PotEng, KinEng, TotEng, Temp, Press, Volume, Density, Pxx, Pyy, Pzz, Pxy, Pxz, Pyz, ]
  - data: [ 2, -479421.7020291921, 0.0102364454473237, -479421.69179274666, 0.11841776952339539, 7835.457865655372, 512, 0.5842697004374003, 7691.6858663982175, 11120.861276811209, 4693.826453756694, 1858.276724547549, 1594.2119834632642, -410.5126868397848, ]
...
---
creator: LAMMPS
timestep: 3
units: real
time: 0.3
natoms: 30
boundary: [ p, p, p, p, p, p, ]
thermo:
  - keywords: [ Step, PotEng, KinEng, TotEng, Temp, Press, Volume, Density, Pxx, Pyy, Pzz, Pxy, Pxz, Pyz, ]
  - data: [ 3, -479421.7325883004, 0.04076112233568721, -479421.69182717806, 0.471534891198419, 7748.0805098520095, 512, 0.5842697004374003, 7604.659889681816, 11027.41110591347, 4612.170533960747, 1848.6311798329627, 1582.3264509138571, -396.7001775021091, ]
...
---
creator: LAMMPS
timestep: 4
units: real
time: 0.4
natoms: 30
boundary: [ p, p, p, p, p, p, ]
thermo:
  - keywords: [ Step, PotEng, KinEng, TotEng, Temp, Press, Volume, Density, Pxx, Pyy, Pzz, Pxy, Pxz, Pyz, ]
  - data: [ 4, -479421.78290842863, 0.09102487713905066, -479421.6918835515, 1.0529986192390275, 7603.17544035678, 512, 0.5842697004374003, 7460.345016690816, 10872.486949658234, 4476.6943547212895, 1832.6646150278937, 1562.6173516148476, -373.7852206394987, ]
...
```

**LAMMPS Version and Platform**

Large-scale Atomic/Molecular Massively Parallel Simulator - 28 Mar 2023 - Development

**To reproduce**

```
compute        press all pressure thermo_temp

dump           myDump all yaml 1 dump.yaml id type x y z fx fy fz  # c_atomicenergies
dump_modify    myDump time yes units yes thermo yes format float "% 10.10e"

thermo_style   custom step pe ke etotal temp press vol density c_press[*]
thermo_modify line yaml format none
thermo         1
```
